# Generated by Django 5.1.2 on 2024-10-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_comment_is_blocked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="auto_reply_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
